click "LivePlayerControlPanel"
put the shouldrepositionmouse into oldSRPM
set the shouldrepositionmouse to NO

(*IF ImageFound("AudioControlsMute")
	click FoundImageLocation()
end if*)

click "LivePlayerControlPanel"
put the shouldrepositionmouse into oldSRPM
set the shouldrepositionmouse to NO

moveto "AudioControls"
drag "AudioSlider"
drop "AudioDown"

(*
IF ImageFound("AudioControlsMute")
	click FoundImageLocation()
end if
*)



